### ISSUE TITLE
Tracking Issue for Demo: Event storm -> Code 

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#1]
# Overview 
The utility of stochastic would be best demonstrated through a useful example app. We'll resurrect Pan-Am airlines for this. 

The story goes roughly like this: 

- Scheduler adds flights to schedule
- I book a ticket
- I select dates, origin, destination
- I select my seat (contention around resources)
- I pay
- I cancel my ticket
- Seat is released
- Cancellation policy does different stuff depending on your status level
- Refund
- Credit
- I check in (traveler)
- I board (gate agent)
- Dispatcher does out, up, on, in
- Loyalty policy awards points
- Dispatcher cancels flight
- Deplane
- Manifest is cleared
- Rebooking policy rebooks according to status

# Event Storm 

- [x] Big picture
- [x] Process model 
- [ ] Software model

## Big Picture 
<img width="2265" alt="Screen Shot 2021-05-03 at 1 41 00 PM" src="https://user-images.githubusercontent.com/824046/116918455-87594f80-ac15-11eb-8dc8-777440a1c539.png">

## Process Model 
<img width="1892" alt="Screen Shot 2021-05-03 at 1 41 41 PM" src="https://user-images.githubusercontent.com/824046/116918486-93dda800-ac15-11eb-9a67-aaaee2d4ef84.png">

## Software model 

TBD

**Comment by sam-goodwin** [comment]
What features are we missing from the current state of the code to support this tracer bullet? A model/pattern for external systems? A consistency model for an aggregate, i.e. `Seating`?

**Comment by ryan-mars** [comment]
Updated the Even Storm to add Software model

**Comment by ryan-mars** [comment]
@sam-goodwin I'm going to start implementing the demo and find out. Off the top of my head... 

- [ ] Bounded Context types/infra/runtime
- [ ] Partition event storm into multiple Cfn stacks 
- [ ] Event subscription across bounded contexts infra/runtime
- [ ] Aggregate types/infra/runtime
- [ ] Event replay types/infra/runtime
- [ ] Command infra/runtime
- [ ] Read model infra/runtime
- [ ] Query infra/runtime

**Comment by sam-goodwin** [comment]
> Partition event storm into multiple Cfn stacks

A single event storm in multiple stacks? Or should a single event storm be tied to a stack. Is this modeled on the declarations of commands/events/policies/etc. or is it where the infrastructure interpreter is configured. Let's create an issue to track each of these items so we can have a detailed discussion and record our decisions.

**Comment by ryan-mars** [comment]
> A single event storm in multiple stacks?

Moving discussion to Bounded Context #7
