### ISSUE TITLE
AggregateRoot

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#11]
- [x] Aggregate.Client fetches event history #24 
- [x] Aggregate reducer/monoid produces current state from events #23
- [ ] Rename Aggregate to AggregateRoot #49
- [ ] Aggregate versioning #50

Maybe later:
- [ ] Convenience functions on `Aggregate` class for declaring Commands and Events that "operate on" the aggregate

> ### “The Aggregate”
> I kept the name ‘aggregate’ mostly for historical reasons, EventStorming was born around Domain-Driven Design and Aggregates, so it makes little sense to look for another name. Aggregates are unit of transactional consistency within a software system. More interestingly they are little state machines that expose consistent behaviour.
> — Alberto Brandolini

<img width="391" alt="Aggregate" src="https://user-images.githubusercontent.com/824046/117174357-3e2f0a00-ad93-11eb-9f14-5ed6803a9d7b.png">

_Illustration ©️ Avanscoperta_

**Comment by ryan-mars** [comment]
Aggregate constructor should also require the `reduce` function for the ordered list of events as well as the `initialValue`.

```typescript
export const FlightScheduleAggregate = new Aggregate({
  __filename,
  key: "flightNo",
  shape: FlightSchedule,
  reducer: (accumulator, event, index, array) => { ... }, 
  initialValue: { ... }
});
```

**Comment by ryan-mars** [comment]
`Aggregate.Client` provided to Command's `Command.Handler` (or `execute`) allows you to fetch an Aggregate by its key. It should provide more than just state (after the reduce has run) it should allow access to the array of events/snapshots as well. Not sure what this should look like but some commands may need to see the list of events for handling difficult situations.

Currently it looks like this. 
```typescript
{
  get: (key) => Promise<some shape>
}
```

Perhaps the return of get could be `{state: ... , events: [ ... ] }`? 

```typescript
{
  get: (key) => Promise<{ state: ... , events: [ ... ] }>
}
```

**Comment by ryan-mars** [comment]
Thought: Commands and Domain Events mostly operate in relation to an Aggregate. Would it not make more sense to have a helper on an aggregate for declaring new Commands (setting the `aggregate` prop) and new Domain Events (defaulting the `source` key).
