### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#4]
- [x] has a shape / is an ADT (provided by superstruct)
- [x] can be validated at runtime from JSON (provided by superstruct)
- [x] is strongly typed (provided by superstruct)
- [x] Simplify Event DX #22
- [x] Event runtime discriminator #21 
- [x] Event needs `source` and `source_id` fields #35
- [x] Re-visit the `payload` boiler-plate in `DomainEvent` #34

**Comment by ryan-mars** [comment]
This seems like too much boiler plate. Need helpers for defining and creating events. Not sure what the exact DX should be though. I guess it would be nice to have a `create(type, {...})` helper for instances. Could not `new Event()` take the structure of the payload and save a step?

```typescript
const FlightCreated = 
    object({ 
      id: string(),
      time: string(),      
      type: literal("FlightCreated"), 
      payload: object({
        flightNo: string(),
        aircraftType: string(),
        origin: string(),
        destination: string()
      })
    })
const FlightCreatedEvent = new Event("FlightCreated", FlightCreated);

//... and then to return an actual event
{
  id: KSUID.randomSync().string,
  time: new Date().toISOString(),
  type: "FlightCreated",
  payload: {
    ...command,
  },
},
```

**Comment by sam-goodwin** [comment]
I was thinking we could borrow the mixin trick from shapes here. 

```
export class FlightCreated extends Event("FlightCreated", object(...)) {}

new FlightCreated({ ... })
```

**Comment by ryan-mars** [comment]
Mixins could work, provided people understand they should not be further extended. I almost wonder if we should just provide a function that returns the class without having to extend the mixin Function. Is there something special about `class ... extends MixinFunc` that couldn't be done with `const FlightCreated = Event("FlightCreated", object(...))`? 

How do we avoid confusing the thing that is an Event (in the graph), with an instance of an Event (data), with a helper function for creating instances? The DX here is not obvious to me.

**Comment by sam-goodwin** [comment]
The function returns a Class, whether the developer extends that or not is up to them. An instance of that class is an event value. I think extending it makes sense to extend it since then you have a type for the event data. 


```
class MyEvent extends Event(..) {}

type MyEventSchema = typeof MyEvent // equiv. in Java would be MyEvent.class

type MyEventData = MyEvent
```

**Comment by sam-goodwin** [comment]
Let's discuss this item next time we meet. I'll try and provide a write up of the DX I'm thinking about

**Comment by ryan-mars** [comment]
Should be using `type` or `kind` to discriminate at runtime?

**Comment by sam-goodwin** [comment]
Maybe we should borrow from graphql, `__typename`.

**Comment by ryan-mars** [comment]
I'm not opposed to `__typename` I want whatever will be the least confusing and most obvious. Since GraphQL shares it could that complicate things for developers at some point if they bolt GraphQL onto the front of a stochastic app?
